// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000007-3)
function tB(Sa)
{fC(1,'Loading Script',Sa);document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+Sa+'"></scr'+'ipt>');}function uB()
{var Ta=this.location.hostname.toLowerCase();var Ua=Ta;intPos1=Ta.indexOf('.');if((intPos1>=0)&&(intPos1<Ta.length))
{intPos2=Ta.indexOf('.',intPos1+1);if(intPos2>intPos1)
Ua=Ta.substring(intPos1+1,Ta.length);}if ((Ua.lastIndexOf('.')==Ua.indexOf('.'))&&Ua.lastIndexOf('.')<3)
Ua=Ta;return Ua;}function vB()
{var Ua=uB();if(Ua=='')
return 'D'+this.location.hostname;else
return 'D'+Ua;}function wB(Va)
{var Ua=uB();if(Va==-1)
{	 if(Ua!='')
	 Ua=' domain='+Ua;	return ';path=/;'+Ua;}var Wa=new Date();if(Ua!='')
Ua=';domain='+Ua;Wa.setTime(parseInt(Wa.getTime(),10)+1000*60*parseInt(Va,10));return ';path=/;expires='+Wa.toGMTString()+Ua;}function xB(j,k,D)
{if(Ads_kid>0)j='0'+j;if(dA!=-1) var intBwdTyp=KAS[dA][4][27];if(typeof(intBwdTyp)=='undefined')
intBwdTyp=0;var i='&dlv='+Ads_nid+','+Ads_wid+','+Ads_iid+','+j+','+k+'&kid='+j+'&chw='+bA+'&tcs='+cA+D+cB+gA;var Xa='&sta=';i+='&dmn='+Ads_T[5];if(navigator.appVersion.substring(0,1)>'3')
{i+='&scx='+screen.width+'&scy='+screen.height+'&scc='+screen.colorDepth;Xa+=',,,'+(navigator.javaEnabled()?'1':'0');if(navigator.javaEnabled())
i+='&jav=1';}else
Xa+=',,,';var Ya=new Date();Xa+=',,,,,,';if((Ads_wrd!='')&&(Ads_wrd.toLowerCase()!='[keyword]'))
{i+='&wrd='+escape(Ads_wrd);Xa+='';}Xa+=','+mD[10]+','+Ads_T[13]+','+intBwdTyp+','+Ads_T[4]+','+Ads_T[10]+','+Ads_T[11]+','+Ads_T[3]+','+Ads_T[12];i+=Xa;if(gbolSUXX25067) i+='&trglog='+escape(gstrXarrTargetDaten);fC(1,'STA-Uri-Parameter',Xa);return (Ads_Timestamp+i);}function yB(j,k,D)
{return '&rdm='+xB(j,k,D)+'&iid='+Ads_iid+'&bid='+k;}function zB()
{return qA[Ads_sec]+(jA?'/red?cmd=red&flg=1&dat=http://a.as-eu.falkag.net/dat/bgf/trpix.gif&':'/dat/bgf/trpix.gif?');}function aC(i)
{fC(1,'',zB()+i);return ((Ads_opt&512)>0)?'':(jC('Ads_Count'+Ads_iid)+'<img src="'+zB()+i+'" width="1" height="1">'+kC());}function bC(y,i)
{y.document.write(aC(i));}function cC()
{return dC(Math.random()*100000000,8);}function dC(Za,Ab)
{var Bb='#'+(Za+100000000);return Bb.substr(10-Ab,Ab);}function eC(Cb,Db,Eb)
{var s;while((s=Cb.indexOf(Db))!=-1)
Cb=Cb.substr(0,s)+Eb+Cb.substring(s+Db.length,Cb.length);return Cb;}function fC(H,Cb,Fb)
{var Gb=new Date();if(Ads_debug==1)
{document.write(((H!=3)?'':'<br>')+'<font color=#0000ff>[DEBUG'+((Gb-hA)/1000)+']</font> ');if((H==0)||(H==3))
document.write('<b><big>'+Cb+'</big></b><br>');else if(H==1)
document.write(''+Cb+': &nbsp;<font color=#000080>'+Fb+'</font><br>');else
document.write('<b>'+Cb+'</b><br>');}else if((Ads_debug==2)&&(H==3))
document.write('<font color=#0000ff>[DEBUG'+((Gb-hA)/1000)+']</font> <b><big>'+Cb+'</big></b><br>');}function gC(Hb)
{var G='#'+(parseInt(Hb,10)+100000000);return G.substr(2,2)+'/'+G.substr(4,2)+'/'+G.substr(6,2)+'/'+G.substr(8,2);}function hC(Za)
{var Ib='0123456789ABCDEF';var Jb='';while(Za>0)
{Jb=Ib.substr(Za%16,1)+Jb;Za=parseInt(Za/16,10);}return (Jb=='')?'0':Jb;}function iC(Kb)
{var Lb;var Mb=0;if(lA>-1)
{Mb=lA;return Mb;}if((Kb==0)&&((Ads_opt&2048)>0))
return -1;if((navigator.userAgent.indexOf("Opera")!=-1)||((navigator.appName=="Netscape")&&(navigator.userAgent.indexOf("Mozilla")!=-1)&&(parseFloat(navigator.appVersion)>=4)))
{if(navigator.mimeTypes&&navigator.mimeTypes["application/x-shockwave-flash"]&&navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin)
{Lb=navigator.plugins['Shockwave Flash'].description;Lb=Lb.substring(Lb.indexOf("."),-1);Mb=Lb.substr(-1);}}else if(navigator.userAgent&&navigator.userAgent.indexOf("MSIE")!=-1&&navigator.userAgent.indexOf("Windows")!=-1&&navigator.userAgent.indexOf("Windows 3")==-1&&document.all)
{document.write('<scr'+'ipt language=VBScript>\n Ads_vbCV=10\nAds_vbMV=1\nDo\nOn Error Resume Next\n');document.write('Ads_vbBF=(IsObject(CreateObject("ShockwaveFlash.ShockwaveFlash."&Ads_vbCV)))\n');document.write('If Ads_vbBF=true Then Exit Do\nAds_vbCV=Ads_vbCV-1\nLoop While Ads_vbCV>=Ads_vbMV\n </scr'+'ipt>');Mb=Ads_vbCV;}lA=Mb;return Mb;}function jC(Nb)
{if(aB)
return '<div id='+Nb+' style="position:absolute;left:-1000;top:-1000;">';else
return '';}function kC()
{if(aB)
return '</div>';else
return '';}function lC(Ob)
{var Pb,Qb;if(window.innerHeight)
{Pb=Ob.x;Qb=Ob.y;}else
{if(Ob.offsetLeft)
{Ob=Ob;Pb=Ob.offsetLeft;Ji=Ob.offsetParent;while(Ji!=null)
{Pb+=Ji.offsetLeft;Ji=Ji.offsetParent;}Qb=Ob.offsetTop;Ji=Ob.offsetParent;while(Ji!=null)
{Qb+=Ji.offsetTop;Ji=Ji.offsetParent;}}else
return [-1000,-1000];}return [Pb,Qb];}function mC(Rb,E,m,n)
{var Sb;var Ob=document.images[E];var Tb=lC(Ob);Ob.width=m;Ob.height=n;if(aB)
Sb=document.getElementById(Rb).style;else if(document.layers)
Sb=document.layers[Rb];else
Sb=document.all[Rb].style;Sb.left=Tb[0];Sb.top=Tb[1];if (aB) Sb.display='block';else if(document.layers) Sb.visibility='show';else Sb.visibility='visible';}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000007-3)
if((typeof(Ads_debug)=='undefined')||(Ads_debug!=1))
window.onerror=sB;gbolSUXX25067=false;var Ads_ModulMain=true;if(typeof(Ads_ModulEffects)=='undefined')
Ads_ModulEffects=false;var bA,cA,dA,eA,fA,gA,hA,iA;var jA,kA,lA,mA,nA,oA;var pA=['http://a.as-eu.falkag.net','https://s.as-eu.falkag.net'];var qA=['http://red.as-eu.falkag.net','https://red.as-eu.falkag.net'];var rA=['http://data.as-eu.falkag.net/server/asldata.js','https://as1.falkag.de/server/asldata.js'];var sA=['http://a.as-eu.falkag.net','https://s.as-eu.falkag.net'];var tA=['http://bw.as-eu.falkag.net','https://s.as-eu.falkag.net'];var uA=[];var vA=navigator.userAgent.toLowerCase();var wA=(vA.indexOf("msie")!=-1);var xA=((vA.indexOf("win")!=-1)||(vA.indexOf("16bit")!=-1));var yA=(vA.indexOf("mac")!=-1);var zA=(navigator.appName.indexOf('icrosoft')!=-1);var aB=(typeof(document.getElementsByTagName)!='undefined'&&typeof(document.createElement)!='undefined')?1:0;var bB=true;var cB='';var dB=0;var eB=[];var fB=[];var gB;var hB=[];var a=[];var b=[];var c=[];var d=[];var e=[];var f=[];var g=[];var Ads_LinkUrl,Ads_CountUrl,Ads_CountUrl_ne,Ads_ClickUrl,Ads_T,iid,bid,rdm;var iB,jB,Ads_gintCurVersion;var kB='toolbar=yes,directories=yes,status=yes,scrollbars=yes,resizable=yes,menubar=yes,location=yes';function gotoSite(){window.open(iB,'flashwin',kB);}function emosite(){window.open(iB,'flashwin',kB);}function FlashClick(){window.open(iB,'flashwin',kB);}function link1(){window.open(iB,'flashwin',kB);}function gotoURL(h){window.open(jB+escape(h),'flashwin',kB);}function lB()
{Ads_kid=0;Ads_bid=0;Ads_cmd='';}function mB(h)
{fC(1,'adsclickurl',Ads_ClickUrl);h=eC(h,'[par]',escape(Ads_par));h=eC(h,'[keyword]',escape(Ads_wrd));h=eC(h,'[timestamp]',Ads_Timestamp);h=eC(h,'[clickurl]',escape(Ads_CountUrl));h=eC(h,'[clickurl_plain]',Ads_CountUrl);h=eC(h,'[web_id]',Ads_wid);h=eC(h,'[web_external_id]',escape(Ads_xwid));h=eC(h,'[con_id]',Ads_iid);h=eC(h,'[con_external_id]',escape(Ads_xiid));return h;}function nB(h,i)
{return qA[Ads_sec]+'/red?cmd=url&'+(jA?'flg=1&':'')+i+'&dat='+escape(h);}function oB(j,k,l,m,n)
{var o;if(dB<2)
{dB++;o=dB+1;cB+='&kid'+o+'='+j;cB+='&bid'+o+'='+k;cB+='&iid'+o+'='+Ads_iid;cB+='&dlv'+o+'='+Ads_nid+','+Ads_wid+','+Ads_iid+','+j+','+k;if(fA!=0)
cB+='&sid'+o+'='+fA;arrIntern=l.split('-');Ads_iid=arrIntern[1];Ads_kid=arrIntern[2];Ads_bid=(arrIntern.length<4)?0:arrIntern[3];Ads_par=(arrIntern.length<5)?Ads_par:unescape(arrIntern[4]);Ads_xl=0;Ads_yl=0;tB(pA[Ads_sec]+'/dat/cjf/'+gC(Ads_iid)+'.js');}else
{fC(1,'Too many internal redirects!!','');cB='';dB=0;lB();}}function pB(p)
{var q=[];var r=p.length;var s;for(s=0;s<r;s+=2)
q[s/2+1]=Ads_CountUrl+escape(p[s+1])+'&bidx='+p[s];return q;}function SAS()
{if (typeof(Ads_T)!='undefined')
{if((document.cookie.toLowerCase().indexOf('bndlvl')==-1)&&((IAS[13]&4)>0))
lD();else
qB();}else
{bB=false;fC(1,'Waiting for asldata.','');}}function qB()
{var t;if((typeof(Ads_debug)=='undefined')||(Ads_debug!=1))
window.onerror=sB;if((0==0)&&((Ads_nid==631)||(Ads_nid==668)))
{ pA[0]=['http://e.as-eu.falkag.net'];sA[0]=pA[0];}if((Ads_nid==80)&&(0==1))
{ pA[0]=['http://e.as-us.falkag.net'];sA[0]=pA[0];}if((Ads_nid==704)&&(0==0))
{var u='#155696#155697#155698#115699#115700#176198#176199#176200#176201#176202#155684#155685#155686#155687#115688#155690#155691#155692#155693#155694#155678#155679#155680#155681#155682#155672#155673#155674#155675#155676#';if (u.indexOf('#'+Ads_iid+'#')!=-1)
{ pA[0]=['http://b.as-eu.falkag.net'];sA[0]=pA[0];}else
{ pA[0]=['http://f.as-eu.falkag.net'];sA[0]=pA[0];}fC(1,'Using CDN',pA[0]);}var v='undefined';if(typeof(Ads_cmd)==v) Ads_cmd='';if(typeof(Ads_kid)==v) Ads_kid=0;if(typeof(Ads_bid)==v) Ads_bid=0;if(typeof(Ads_xl)==v) Ads_xl=0;if(typeof(Ads_yl)==v) Ads_yl=0;if(typeof(Ads_xp)==v) Ads_xp='';if(typeof(Ads_yp)==v) Ads_yp='';if(typeof(Ads_opt)==v) Ads_opt=0;if(typeof(Ads_wrd)==v) Ads_wrd='';if(typeof(Ads_prf)==v) Ads_prf='';if(typeof(Ads_par)==v) Ads_par='';if(typeof(Ads_cnturl)==v) Ads_cnturl='';if(typeof(Ads_ref)==v) Ads_ref=0;if(typeof(Ads_anc)==v) Ads_anc='';if(typeof(Ads_cmb)==v) Ads_cmb=[];if(typeof(Ads_uid)==v) Ads_uid='';if(typeof(Ads_bgc)==v) Ads_bgc='';Ads_cmd=Ads_cmd.toLowerCase();if(Ads_ref==0)
Ads_ref=IAS[12];if(Ads_bgc=='')
{if(typeof(IAS[16])!=v)
Ads_bgc=IAS[16];}t=pA[Ads_sec]+'/dat/dlv/aslframe.html?dat='+Ads_iid +'&kid='+Ads_kid+'&wrd='+escape(Ads_wrd) +'&bid='+Ads_bid+'&prf='+escape(Ads_prf) +'&xl='+Ads_xl+'&par='+escape(Ads_par) +'&yl='+Ads_yl+'&cnturl='+Ads_cnturl+'&debug='+Ads_debug +'&xp='+Ads_xp+'&sec='+Ads_sec+'&bgc='+Ads_bgc +'&yp='+Ads_yp+'&ref='+Ads_ref+'&opt=';var w='" width="'+Ads_xl+'" height="'+Ads_yl+'" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>';if(Ads_ref>0)
{document.write('<iframe src="'+t+Ads_opt+w);Ads_ref=0;return;}fC(3,'Start for Adspot '+Ads_iid);uD();if((Ads_bgc!='')&&(Ads_bgc!='-1'))
document.body.style['backgroundColor']='#'+Ads_bgc;if(((IAS[13]&8)>0)&&(mD[10]==0))
iD();bA='';cA='';eA=0;fA=0;gA='';dA=-1;if(0==1)
KAS[KAS.length]=[-1,100,-1,100,[],0,0,0,0,100];fC(3,'Select campaigns');if((Ads_kid==0)||(Ads_kid==''))
dA=qC();else
{fC(1,'Preselected campaign',Ads_kid);r=KAS.length;dA=0;while((dA<r)&&(KAS[dA][0]!=Ads_kid))
dA++;if(dA==r)
dA=-1;}if((Ads_opt&256)!=0)
{if(dA!=-1)
Ads_skid=KAS[dA][0];else
Ads_skid=0;fC(1,'Skipping delivery,selected campaign:',Ads_skid);}else
{if(dA!=-1)
{eA=KAS[dA][0];fA=KAS[dA][6];if(fA!=0)
gA='&sid='+fA;fC(1,'Selected campaign',eA+'('+fA+')');if(eA>0)
{fC(1,'BJF-load start','');tB(pA[Ads_sec]+'/dat/bjf/'+gC(eA)+'.js');fC(1,'BJF-load ende','');}else
DAS();}else
{fC(1,'no campaign selected!','');DAS();}}}function DAS()
{fC(3,'Select banner for campaign '+eA);var x,r,i,y,z,A,B,C;var D='';var E='';var F=['_blank','_self','_parent','_top'];var k=0;var G,m,n;if(IAS[9]==1)
{G='adsolut.gif';m=234;n=60;}else
{G='trpix.gif';m=1;n=1;}mA='AdSolution';if(IAS[9]==4)
mA='Werbung';mA='onmouseover="self.status=\''+mA+'\';return true;" ';if(IAS[9]==5)
mA='';var H=1;var h='http://www.falkag.de';// Ziel-Url
var I='Falk AdSolution';var J=0;var K='';var L='';var M='';var N='';var O='';var P=0;var Q=0;var R=1;var S=2;var l='';var T='';var p=[];var U=0;var V='';var W='';var X=false;var Y,Z,Aa,Ba,Ca,Da,Ea,Fa,Ga,Ha;if(eA!=0)
{if((Ads_bid==0)||(Ads_bid==''))
x=rC(dA,eA);else
{r=BAS.length;x=0;while((BAS[x][0]!=Ads_bid)&&(x<r))
x++;if(x==r)
x=-1;}if(x!=-1)
k=BAS[x][0];}if(k>0)
{H=BAS[x][3];G=BAS[x][4];h=BAS[x][5];I=BAS[x][6];J=BAS[x][12];K=BAS[x][7];L=BAS[x][8];M=BAS[x][9];N=BAS[x][10];O=BAS[x][11];m=BAS[x][13];n=BAS[x][14];P=BAS[x][15];Q=BAS[x][16];R=BAS[x][17];S=BAS[x][18];l=BAS[x][19];T=BAS[x][20];p=BAS[x][22];U=BAS[x][23];V=BAS[x][24];W=BAS[x][25];Ads_klist+=eA+'#';A=KAS[dA][4][25];if(A>0)
{if(typeof(Ads_fcount[A])=='undefined')
Ads_fcount[A]=1;else
Ads_fcount[A] ++;}}if(eA>0)
D=wD(eA,dA,k,x,((J&4096)>0));if(eA==-1)
{eA=99999999;k=99999999;}Ads_skid=eA;Ads_sbid=k;fC(1,'Selected campaign',eA);fC(1,'Selected banner',k);fC(3,'Delivery and display of the banner');L=(L=='')?h:L;Y=(J&24);Z=F[J&3];Ca=((J&64)>0)&&((Ads_opt&64)==0);Aa=(J&128)>0;Ba=(J&512)>0;X=(V=='_search')||(V=='_media');Da=((J&1024)>0)&&Ads_ModulEffects;Ea=((J&8192)>0);Fa=(J&2048)>0;Ga=(T.length>0);m=(Ads_xl>0)?Ads_xl:m;n=(Ads_yl>0)?Ads_yl:n;P=(Ads_xp!='')?Ads_xp:P;Q=(Ads_yp!='')?Ads_yp:Q;jA=(J&4096)>0;Ads_opt|=(J&16384)>0?64:0;Ads_opt|=IAS[3]*32;if(Ads_anc!='')
{B=true;E=Ads_anc;Ads_anc='';}Ads_Timestamp=cC();h=mB(h);L=mB(L);if(Ads_cnturl!='')
{Ha=eC(Ads_cnturl,'[url]',escape(h));h=eC(Ha,'[url_plain]',h);Ha=eC(Ads_cnturl,'[url]',escape(L));L=eC(Ha,'[url_plain]',L);}if(eB.length!=0)
{bA+=eB[13];cA+=eB[14];}i=yB(eA,k,D);fC(1,'Count-String',i);if((H==3)||(H==4)||(H==8))
{Ads_LinkUrl=h;Ads_CountUrl=nB('',i);Ads_CountUrl_ne=Ads_CountUrl.substr(0,Ads_CountUrl.length-1)+'ne=';Ads_ClickUrl=Ads_CountUrl+escape(h);Ads_MultiUrl=pB(p);Ads_ViewCode=aC(i);Ads_ViewUrl=zB()+i;}if(H==1)
M=sA[Ads_sec]+'/dat/bgf/'+G;if(eB.length!=0)
{if(!Aa)
{Aa=eB[0];Ca=eB[1];Ba=eB[2];S=eB[3];Da=eB[4];Ea=eB[5];}if(!Ga)
{Ga=eB[6];T=eB[7];}P=eB[8];Q=eB[9];Y=eB[10];IAS[2]=eB[11];IAS[11]=eB[12];E=eB[15];B=(E!='');eB=[];}if(H==5)
{eB=[Aa,Ca,Ba,S,Da,Ea,Ga,T,P,Q,Y,IAS[2],IAS[11],bA,cA,E];Aa=false;Ga=false;B=false;IAS[2]=0;}if((Ads_cmd=='lnk')&&(H!=5))
{self.location.href=nB(h,i);Aa=false;Ga=false;B=false;H=6;return;}if(Aa&&!X)
{y=aH(m,n,P,Q,Y,Ca,Ba,S,Da,Ea);if(Ca)
{if(window.innerHeight)
{m=y.innerWidth;n=y.innerHeight;}else
{m=y.document.body.clientWidth;n=y.document.body.clientHeight;}}if(Ba)
window.setTimeout('y.blur();',S*1000);}else
y=window;if(B)
document.write(jC('Ads_place'+Ads_iid));else if(Ads_ModulEffects&&Ga)
{if(Y==16)
Y=1;else if(Y==24)
Y=2;else
Y=0;hG(Ads_iid,m,n,P,Q,Y,T,Aa,y);iG(Ads_iid,Ads_sec);}fC(1,'Banner-Typ/PopUp',H+'/'+Aa);if(H<2)
uG(y,Aa,i,M,h,Z,m,n,I);else if(H==2)
vG(y,Aa,i,G,h,Z,m,n,I,K,L,Fa,R,W);else if(H==3)
wG(y,Aa,i,eA,k,D,Ga,m,n,U,V,B,'/dat/brf/',0,X);else if(H==4)
xG(y,Aa,i,N,O,Ga,m,n,B);else if(H==5)
oB(eA,k,l,m,n);else if(H==8)
wG(y,Aa,i,eA,k,D,Ga,m,n,U,V,B,'/dat/bfx/',parseInt(l,10),X);fC(3,'Banner-display finished');jD();if(B)
{document.write(kC());setInterval('mC("Ads_place'+Ads_iid+'","'+E+'",'+m+','+n+');',20);}if(Ads_ModulEffects&&Ga)
jG(Ads_iid);if(H!=5)
lB();Ads_idl+='#'+Ads_iid+'#';if((IAS[2]>0)&&(Ads_idl.indexOf('#'+IAS[2]+'#')==-1)&&(IAS[11]>(Math.random()*100)))
{fC(1,'Load adspot-combined adspot',IAS[2]);Ads_kid=0;Ads_bid=0;Ads_xl=0;Ads_yl=0;tB(pA[Ads_sec]+'/dat/cjf/'+gC(IAS[2])+'.js');}r=Ads_cmb.length;for(s=0;s<r;s++)
{if(Ads_cmb[s]!='')
{C=Ads_cmb[s];Ads_cmb[s]='';s=r;Ads_pth='';Ads_iid='';eval(C);fC(1,'Load tag-combined adspot',Ads_iid+Ads_pth);if(Ads_pth!='')
tB(pA[Ads_sec]+'/dat/njf/'+Ads_pth+'.js');else
tB(pA[Ads_sec]+'/dat/cjf/'+gC(Ads_iid)+'.js');}}}function CAS()
{if(typeof(Ads_debug)=='undefined') Ads_debug=0;var Ia=new Date(Ads_T[9]);var Ja=new Date();Ads_T[9]=Ia-Ja;var Ka=Ads_T[0]+'#'+Ads_T[1]+'#'+Ads_T[2]+'#'+Ads_T[3]+'#'+Ads_T[4]+'#'+Ads_T[5]+'#'+Ads_T[6]+'#'+escape(Ads_T[7])+'#'+escape(Ads_T[8])+'#'+Ads_T[9]+'#'+Ads_T[10]+'#'+Ads_T[11]+'#'+Ads_T[12]+'#'+Ads_T[13];document.cookie='ASLTRG='+Ka+wB(60*24);fC(1,'Load targeting-infos from server',Ka);if (bB==false)
{SAS();bB=true;}}function LAS(La)
{Ads_iid=0;var i='pth='+La+'&xl='+Ads_xl+'&yl='+Ads_yl;if(typeof(Ads_channels)!='undefined')
i+='&chn='+escape(Ads_channels);jA=false;document.write(aC(i));}function rB()
{hA=new Date();lA=-1;oA=0;document.cookie='BSUID=1'+wB(60*24*30);kA=false;if(typeof(Ads_debug)=='undefined') Ads_debug=0;if(typeof(Ads_sec)=='undefined') Ads_sec=0;if(typeof(Ads_opt)=='undefined') Ads_opt=0;if(typeof(Ads_klist)!='string') Ads_klist='';if(typeof(Ads_fcount)!='object') Ads_fcount=[];if(typeof(Ads_idl)!='string') Ads_idl='';if(typeof(garrIFrames)=='undefined') garrIFrames=[];fC(3,'Global Init');var Ka=document.cookie+';';var Ma=(Ka.indexOf('BSUID=')!=-1);var Na=Ka.indexOf('ASLTRG=');var Oa,Z;if(Na!=-1)
{Oa=Ka.indexOf(';',Na);Z=Ka.substring(Na+7,Oa);Ads_T=Z.split('#');Ads_T[7]=unescape(Ads_T[7]);Ads_T[8]=unescape(Ads_T[8]);fC(1,'Load targeting-infos from cookie',Z);}else
{fC(1,'#-#ASLDATA-load start','');tB(rA[Ads_sec]+(Ma?('?rdm='+cC()):''));fC(1,'#-#ASLDATA-load ende','');}}function sB(Pa,Qa,Ra)
{return true;}rB();// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000007-3)
function tG(Cg,Ki)
{return (Cg==0)?'':' '+Ki+'="'+Cg+'"';}function uG(y,Aa,i,M,h,Z,m,n,I)
{M=mB(M);if(Aa)
yG(y,I);y.document.write('<a href="'+nB(h,i) +'" target="'+Z+'" '+mA+'onmouseout="self.status=\'\';return true;">');y.document.write('<img src="'+M+'"'+tG(m,'width')+tG(n,'height')+' border="0" id="Ads_img'+Ads_iid+'" name="Ads_img'+Ads_iid+'" alt="'+I+'"></a>');bC(y,i);if(Aa)
zG(y);cB='';dB=0;}function vG(y,Aa,i,G,h,Z,m,n,I,K,L,Fa,R,W)
{var Li=eC(i,'&rdm='+Ads_Timestamp,'');if(Aa)
yG(y,I);h=nB(h,Li);L=nB(L,Li);G=sA[Ads_sec]+'/dat/bgf/'+G;K=sA[Ads_sec]+'/dat/bgf/'+K;iB=h;jB=nB('',Li);var Mi=G;if(typeof(W)=='undefined') W='';if(W=='')
Mi+='?clickTag='+escape(h)+'&url='+escape(h);else if(W!='0')
Mi+='?'+W+'='+escape(h);fC(1,'Flash-Url',Mi);var Lb;if(R<=iC(1))
{y.document.write('<OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http'+((Ads_sec==1)?'s':'')+'://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=3,0,0,0" id=banner'+tG(m,'width')+tG(n,'height')+'">');y.document.write('<PARAM NAME=movie VALUE="'+Mi+'"><PARAM NAME=play VALUE=true><PARAM NAME=autoplay VALUE=true><PARAM NAME=wmode VALUE=opaque><PARAM NAME=quality VALUE=autohigh><PARAM name=scale value=exactfit>');y.document.write('<EMBED src="'+Mi+'" quality=autohigh autoplay=true play=true wmode=opaque scale=exactfit swLiveConnect=TRUE'+tG(m,'width')+tG(n,'height')+' TYPE="application/x-shockwave-flash" PLUGINSPAGE="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash"></EMBED></OBJECT>');}else
{y.document.write('<a href="'+L+'" target="'+Z+'" '+mA+' onmouseout="self.status=\'\';return true;"><img src="'+K+'"'+tG(m,'width')+tG(n,'height')+' border="0" alt="'+I+'"></a>');}bC(y,i);if(Aa)
zG(y);cB='';dB=0;}function wG(y,Aa,i,j,k,D,Ga,m,n,U,V,B,La,Ni,X)
{var G=pA[Ads_sec]+La+gC((Ni>0)?Ni:((U==0)?k:U));var Oi,Ye;iid=Ads_iid;bid=k;rdm=xB(j,k,D);if(Aa||((Ga||B)&&(zA||aB)))
{var Pi='*';for(Ye=1;Ye<Ads_MultiUrl.length;Ye++)
{h=Ads_MultiUrl[Ye];Pi+=h.substring(Ads_CountUrl.length,h.length)+'*';}Oi=Ads_wid+'#'+Ads_iid+'#'+j+'#'+k+'#'+Ads_xwid+'#'+Ads_xiid+'#'+Ads_wrd+'#'+Ads_prf+'#'+Ads_par+'#'+Ads_Timestamp+'#'+rdm+'#'+(qA[Ads_sec]+'/red?cmd=url&'+(jA?'flg=1&':''))+'#'+Ads_LinkUrl+'#'+Pi+'#'+zB();}if(Aa&&X)
{fC(1,'Sidebar',G+'.html?'+escape(Oi));window.open(G+'.html?'+escape(Oi),V);}else if(Aa)
{fC(1,'Pop',G+'.html?'+escape(Oi));y.location.href=G+'.html?'+escape(Oi);}else if((Ga||B)&&(zA||aB))
{fC(1,'Ifr',G+'.html?'+escape(Oi));document.write('<iframe src="'+G+'.html?'+escape(Oi)+'" width="'+m+'" height="'+n+'" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>');}else
{fC(1,'Jsc',G+'.js');if(Ni>0)
{Ads_xl=m;Ads_yl=n;bC(y,i);tB(pA[Ads_sec]+'/dat/dlv/afxplay.js');}tB(G+'.js');}cB='';dB=0;}function xG(y,Aa,i,N,O,Ga,m,n,B)
{O=mB(unescape(O));N=mB(unescape(N));fC(1,'Redirect',O+'/'+N);if(Aa)
y.location.href=N;else
{if(((Ga||B)&&zA)||(O==''))
document.write('<iframe src="'+N+'" width="'+m+'" height="'+n+'" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>');else
tB(O);}bC(window,i);cB='';dB=0;}function yG(y,I)
{y.document.open();y.document.write('<html><head><title>'+I+'</title></head><body topmargin="0" leftmargin="0" rightmargin="0" marginwidth="0" marginheight="0"><table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0" align="center"><tr><td valign="middle"><center>');}function zG(y)
{y.document.write('</center></td></tr></table></body></html>');y.document.close();}function aH(m,n,P,Q,Y,Ca,Ba,S,Da,Ea,X,V)
{var z='locationbar=no,directories=no,statusbar=no,toolbar=no,location=no,menubar=no,personalbar=no';var Qi='Ads_Popup'+Ads_iid;var Ri,Si;var Ti=0;var Ui=0;if (!X&&V!='')
Qi=V;if(Ca)
{if (xA)
{Ti=10;Ui=30;}else if (yA)
{Ti=20;Ui=35;}z+=',scrollbars=no,resizable=no,width='+(screen.availWidth-Ti)+',height='+(screen.availHeight-Ui)+',screenX=0,screenY=0';if(wA)
z='fullscreen=yes';}else
{if(Da)
z+=',resizable=yes,width=90,height=70,innerWidth=90,innerHeight=70';else
z+=',resizable=no,width='+m+',height='+n;if(Ea)
z+=',scrollbars=yes';else
z+=',scrollbars=no';if((Ads_opt&64)>0)
z='locationbar=yes,scrollbars=yes,directories=yes,statusbar=yes,toolbar=yes,location=yes,menubar=yes,personalbar=yes,resizable=yes,width='+m+',height='+n;if(Y==16)
{P=(screen.width-m-25)*P/100;Q=(screen.height-n-50)*Q/100;}else if(Y==24)
{P=(screen.width-m-25)*Math.random();Q=(screen.height-n-50)*Math.random();}if (!zA)
z+=",screenX="+P+",screenY="+Q;else
z+=",left="+P+",top="+Q;}if((Ads_opt&32)>0)
Qi+=''+Math.round(Math.random()*100000);fC(1,'PopUp open START','');y=open('',Qi,z);fC(1,'PopUp open END','');if(Ca&&(!wA))
y.moveTo(0,0);if(Ba&&(S==0))
y.blur();else if(Ba)
y.setTimeout('window.blur();',S*1000);if(Da)
qG(y,m,n);return y;}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000007-3)
var mD=[];var nD;function oD(Of,Pf,Qf)
{if(typeof(Of)=='undefined')
return [];var s,r;var Rf=[];var Sf=Of.split('x');var Tf=Sf[0];var Uf=Pf-Tf;var r=Sf.length;for(s=1;s<r;s++)
{Ah=Sf[s].split(':');if(Qf&&(Ah[2]==-1))
Rf[Ah[0]]=[Ah[1],-1];Ah[2]-=Uf;if(Ah[2]>0)
Rf[Ah[0]]=[Ah[1],Ah[2]];}return Rf;}function pD(Rf,Pf)
{var Nb;var Of=Pf;for(Nb in Rf)
Of+='x'+Nb+':'+Rf[Nb][0]+':'+Rf[Nb][1];return Of;}function qD(Vf,Wf)
{while(Vf.length>800)
Vf=Vf.substr(0,Vf.lastIndexOf('#',Vf.length-2)+1);mD[Wf]=Vf;}function rD(Wf,Hb)
{var Xf='111';var Yf='@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`';var r=0;var Zf='#'+Hb+':';var Vf=mD[Wf];var Ag='';var Y=Vf.indexOf(Zf);var Bg=new Date();var Cg,Dg,Eg,Fg,Dd;var Gg,Hg,Ig,Jg;if(Vf=='')
Vf='#';if(Y>-1)
{Dg=Vf.substr(Y+Zf.length,3+Wf);if(Y>0)
Ag=Vf.substr(0,Y);Cg=Vf.length-Y-Zf.length-3-Wf;if(Cg>0)
Ag+=Vf.substr(Y+Zf.length+3+Wf,Cg);Vf=Ag;Eg=new Date(Yf.indexOf(Dg.charAt(0))+2000,Yf.indexOf(Dg.charAt(1))-1,Yf.indexOf(Dg.charAt(2)));Bg.setHours(0);Bg.setMinutes(0);Bg.setSeconds(0);Fg=(Bg.getTime()-Eg.getTime())/1000/60/60/24;intAltWTag=(Eg.getDay()==0?7:Eg.getDay());intNeuWTag=(Bg.getDay()==0?7:Bg.getDay());intAltMTag=Eg.getDate();intNeuMTag=Bg.getDate();Xf=((Fg>0.1)?'1':'0')+(((Fg>6)||(intAltWTag>intNeuWTag))?'1':'0')+(((Fg>29)||(intAltMTag>intNeuMTag))?'1':'0');if(Wf==1)
r=Yf.indexOf(Dg.charAt(3));}Dg='#'+Hb+':';Dd=Bg.getYear();if(Dd<1900)
Dd+=1900;Dg+=Yf.charAt(Dd-2000);Dg+=Yf.charAt(Bg.getMonth()+1);Dg+=Yf.charAt(Bg.getDate());if(Wf==1)
{r++;if(r>21)
r=21;Dg+=Yf.charAt(r);Xf+=Yf.charAt(r);}Vf=Dg+Vf;qD(Vf,Wf);return Xf;}function sD(Zf,Wf,Kg)
{var Na,Oa,Cg,Lg,Mg;var Vf=mD[Wf];var Ag='';var Ng='';var Og=-1;if(Vf=='')
Vf='#';Zf='#'+Zf+'-';Na=Vf.indexOf(Zf);if(Na!=-1)
Oa=Vf.indexOf('#',Na+1);if((Na!=-1)&&(Oa!=1))
{Lg=Vf.substring(Na+Zf.length,Oa);if(Na>0)
Ag=Vf.substr(0,Na);Cg=Vf.length-Oa;if(Cg>0)
Ag+=Vf.substr(Oa,Cg);Vf=Ag;if(Wf==6)
{Mg=Lg.split('-');Ng=Mg[0];Lg=Mg[1];}Og=Kg-parseInt(Lg,10);if(Og>1200)
Og=-1;}mD[Wf]=Vf;return [Og,Ng];}function tD(j)
{var Pg=new Date();var Og=Pg.getHours()*60*60+Pg.getMinutes()*60+Pg.getSeconds();var Qg,Rg;Qg=sD(Ads_wid,6,Og);Rg=sD(j,5,Og);var Sg=(Qg[0]==-1);var Tg=(Rg[0]==-1);var Ug=(Sg?'1':'0')+(Tg?'1':'0');if(!Sg)
Ug+=dC(Qg[0],4)+Qg[1];qD('#'+Ads_wid+'-'+Ads_iid+'-'+Og+mD[6],6);qD('#'+j+'-'+Og+mD[5],5);return Ug;}function uD()
{iA=vB();fC(2,'Read Cookies');var s,Vg,Nb,Wg,Xg,Yg,Zg,Ah,Wf;var Ka=document.cookie;var Qf=(Ka.toLowerCase().indexOf('sestest')>-1);document.cookie=iA+'SESTEST=1'+wB(-1);var Bh=Ka.split(';');var r=Bh.length;var Gb=new Date();nD=Math.round(Gb.getTime()/1000/60);mD=['','',[],'','','','',[],[],[],oA,'',[]];for(s=0;s<r;s++)
{Wf=-1;Yg=Bh[s].split('=');Nb=Yg[0];Xg=Yg[1];if(Nb.charAt(0)==' ')
Nb=Nb.substr(1,Nb.length-1);if(Nb.substr(0,iA.length)==iA)
Wg=Nb.substring(iA.length,Nb.length);else
Wg='';if(Wg=='KIDYMD')
mD[1]=Xg;else if(Wg=='WIDYMD')
mD[0]=Xg;else if(Nb=='BSUID')
mD[3]=Xg;else if(Nb=='BNDWDT')
mD[4]=Xg;else if(Nb=='BNDLVL')
mD[10]=Xg;else if(Wg=='VISKAM')
mD[5]=Xg;else if(Wg=='VISWEB')
mD[6]=Xg;else if(Wg=='FRQSTR')
{Yg=Xg.split(',');fC(1,'KID',Yg[0]);fC(1,'WID',Yg[1]);fC(1,'NID',Yg[2]);fC(1,'BID',Yg[3]);fC(1,'FID',Yg[4]);mD[2]=oD(Yg[0],nD,Qf);mD[7]=oD(Yg[1],nD,Qf);mD[8]=oD(Yg[2],nD,Qf);mD[9]=oD(Yg[3],nD,Qf);mD[12]=oD(Yg[4],nD,Qf);}}if(Ads_uid!='')
{Bh=Ads_userdata.split(';');r=Bh.length;mD[2]=[];for(s=1;s<(r-1);s++)
{Yg=Bh[s].split(',');mD[2][Yg[0]]=[Yg[1],1];}}if(mD[3]=='1')
kA=true;fC(1,'COOKIES',kA);fC(1,'KIDYMD',mD[1]);fC(1,'WIDYMD',mD[0]);fC(1,'BSUID' ,mD[3]);fC(1,'BNDWDT',mD[4]);fC(1,'BNDLVL',mD[10]);fC(1,'VISKAM',mD[5]);fC(1,'VISWEB',mD[6]);}function vD(j,Jc)
{var Ch,Dh,Yc,Eh;var Fh='';iA=vB();var Gh=KAS[Jc][4][5];if(KAS[Jc][4][4]>0)
Fh=wB(Gh);else if((KAS[Jc][5]&1)>0)
{Fh=wB(20);Gh=20;}if(Fh!='')
{Yc=parseInt(xD(j,2)+1,10);if(Ads_uid!='')
{Ch=Ads_userdata.split(';'+j+',');if(Ch.length==2)
{Dh=Ads_userdata.split(','+j+';');Ads_userdata=Ch[0]+';'+Dh[1];}Ads_userdata+=j+','+Yc+','+Gh+','+j+';';Eh=new Image();Eh.src='http://uboot.as-eu.falkag.net/usr?cmd=write&id='+Ads_uid+'&data='+Ads_userdata+'&rdm='+Math.random();fC(1,'tp','?cmd=write&id='+Ads_uid+'&data='+Ads_userdata+'&rdm='+Math.random());}else
yD(j,2,Yc,Gh);}}function wD(j,Jc,k,x,Hh)
{iA=vB();var D,Ka;vD(j,Jc);if(k>0)
{if(BAS[x][2][4]>0)
yD(k,9,xD(k,9)+1,BAS[x][2][5]);}if(((KAS[Jc][4][22]&1)>0)&&(IAS[4]>0))
yD(Ads_wid,7,xD(Ads_wid,7)+1,IAS[5]);if(((KAS[Jc][4][22]&2)>0)&&(IAS[6]>0))
yD(Ads_nid,8,xD(Ads_nid,8)+1,IAS[7]);if ((typeof(IAS[17])!='undefined')&&(typeof(hB[Ads_wid])!='undefined')&&(typeof(KAS[Jc][13])!='undefined'))
{if(((KAS[Jc][4][22]&4)>0)&&(KAS[Jc][13]>0)&&(hB[Ads_wid].length>0)&&(typeof(hB[Ads_wid][KAS[Jc][13]])!='undefined'))
{arrFamily=hB[Ads_wid][KAS[Jc][13]];yD(arrFamily[0],12,xD(arrFamily[0],12)+1,arrFamily[2]);}}Ka=pD(mD[2],nD)+',' +pD(mD[7],nD)+',' +pD(mD[8],nD)+',' +pD(mD[9],nD)+',' +pD(mD[12],nD);document.cookie=iA+'FRQSTR='+Ka+wB(60*24*365);D=rD(1,j);D='&bls3='+D.substr(0,3)+rD(0,Ads_wid)+D.substr(3,1);document.cookie=iA+'WIDYMD='+mD[0]+wB(60*24*30);document.cookie=iA+'KIDYMD='+mD[1]+wB(60*24*30);D+='&bls4='+tD(j);document.cookie=iA+'VISKAM='+mD[5]+wB(20);document.cookie=iA+'VISWEB='+mD[6]+wB(20);if(kA)
D+='&uid=1';return D;}function xD(Hb,Ld)
{if(typeof(mD[Ld][''+Hb+''])!='undefined')
return parseInt(mD[Ld][''+Hb+''],10);else
return 0;}function yD(Hb,Ld,Yc,Gh)
{if(typeof(mD[Ld][''+Hb+''])!='undefined')
mD[Ld][''+Hb+''][0]=Yc;else
mD[Ld][''+Hb+'']=[Yc,Gh];}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000007-3)
function nC(Ub,Vb)
{fC(1,'Select-Value',Vb);var s=0;var r=Ub.length;if(r==0)
return -1;while((s<r-1)&&(Vb>Ub[s][1]))
{Vb-=Ub[s][1];s++;}return Ub[s][0];}function oC(Wb,Xb,Yb)
{var s,Zb,Ac,Bc;fC(1,'---- CLOSE OLD PRIORITY','');fC(1,'share-sum of all successfully campaigns',Wb);fC(1,'free shares before this priority',Yb);if(Wb>Yb)
{Zb=Yb/Wb;for(s=Xb;s<uA.length;s++)
uA[s][1]*=Zb;Wb=Yb;}Yb-=Wb;fC(1,'free shares after this priority',Yb);return Yb;}function pC()
{fC(0,'campaign-filtering');var Cc,Dc,Ec,Fc,Gc;var Hc=-2;var Ic=KAS.length;var Yb=100;var Jc,j,Bc,Kc,Lc,Mc,Nc,Oc,Pc;var Wb=0;var Xb;uA=[];for (Jc=0;Jc<Ic;Jc++)
{Gc=((KAS[Jc][5]&2)>0);if(KAS[Jc][2]!=Hc)
{if(Hc!=-2)
Yb=oC(Wb,Xb,Yb);Hc=KAS[Jc][2];fC(1,'---- START NEW PRIORITY',Hc);Wb=0;Xb=uA.length;}fC(1,'<b>campaign '+KAS[Jc][0]+'</b>',KAS[Jc]);Kc=KAS[Jc][8];Lc=KAS[Jc][10];Mc=IAS[10];if((Mc-Lc)>0)
Kc=Kc*Mc/(Mc-Lc);Bc=KAS[Jc][1];if(Kc<=0)
Kc=Bc;Nc=(Bc/Kc-1)*2+1;var Qc=Nc;var Rc=false;if (Nc>10||Nc<0.1)
Rc=true;if(Nc>10)
Nc=10;else if (Nc<0.1)
Nc=0.1;if (Rc)
fC(1,'Factor (before:after)',Qc+':'+Nc);Oc=KAS[Jc][3];Bc=Bc*Nc*100/((Oc==0)?100:Oc);if(isNaN(Bc))
Bc=0;Fc=KAS[Jc][4];Cc=hD(Fc,0,KAS[Jc][0],((KAS[Jc][5]&4)>0),Jc);Ec=false;if(Fc.length>0)
{Ec=((Fc[0]==0)&&!((Fc[2]==0)&&(Fc[3]==1439)));Dc=(!Ec||fD(Fc[2],Fc[3]));if(Ec)
Bc=Bc*100/KAS[Jc][9];if(Cc&&!Dc&&!Gc)
bA+='9'+KAS[Jc][0]+'-';Cc=(Cc&&Dc);}if((KAS[Jc][5]&8)>0)
Bc=KAS[Jc][1];fC(1,'timetargeting,successful',(Ec)+','+(Dc));if(Gc&&Cc)
{fC(2,'<font color=#ff8000>testcase successful</font>');j=KAS[Jc][0];cA+=j+'-';vD(j,Jc);}else if(Cc)
{fC(2,'<font color=#008000>successful</font>');uA[uA.length]=[Jc,Bc,Ec,Bc];Wb+=Bc;}else
{fC(2,'<font color=#ff0000>failed</font>');}}Yb=oC(Wb,Xb,Yb);}function qC()
{pC();var Sc,Jc,s,Bc;var Ic=uA.length;var Tc=0;fC(0,'campaign-selection');for (Jc=0;Jc<Ic;Jc++)
{s=uA[Jc][0];Bc=uA[Jc][1];Sc=Math.round(Bc/uA[Jc][3]*10)-1;if(Sc>9)
Sc=9;if((Sc>0)&&(KAS[s][0]>0))
bA+=Sc+''+KAS[s][0]+'-';Tc+=Bc;fC(1,'Campaign,Chance,ShareActual,Share,ShareNew',KAS[s][0]+' ,'+KAS[s][3]+' ,'+KAS[s][8]+' ,'+KAS[s][1]+' ,'+Bc);}fC(1,'Chances',bA);return nC(uA,Tc*Math.random());}function rC(Jc,j)
{var Uc=[];var Vc=BAS.length;var Wc=((KAS[Jc][5]&1)>0);var Tc=0;var x,Bc,Xc,Yc,Zc,Ad;var Bd=true;for (x=0;x<Vc;x++)
{fC(1,'<b>Banner '+BAS[x][0]+'</b>',BAS[x]);strInhalt=BAS[x][21];Ad=((strInhalt.length<3)||(strInhalt.indexOf('#'+Ads_iid+'#')>-1));if(((Ads_xl>1)||(Ads_yl>1))&&((BAS[x][13]>1)||(BAS[x][14]>1)))
{Bd=((Ads_xl==BAS[x][13])&&(Ads_yl==BAS[x][14]));fC(1,'Bannersize',Bd);}if(Bd&&Ad&&hD(BAS[x][2],1,BAS[x][0],true,x))
{Bc=BAS[x][1];fC(2,'<font color=#008000>successful</font></b>,Anteil:'+Bc+'<b>');Uc[Uc.length]=[x,Bc];Tc+=Bc;}else
{fC(2,'<font color=#ff0000>failed</font>');}}Vc=Uc.length;if(Wc)
{Yc=xD(j,2);if(Vc>0)
x=Uc[Yc%Vc][0];else
x=-1;}else
x=nC(Uc,Tc*Math.random());return x;}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000007-3)
var sC=false;var tC;var uC;var vC=0;function wC(Cd)
{return dC(Cd.getHours(),2)+':'+dC(Cd.getMinutes(),2)+':'+dC(Cd.getSeconds(),2);}function xC(Cd)
{var Dd=Cd.getYear();if(Dd<1900)
Dd+=1900;return dC(Dd,4)+'-'+dC(Cd.getMonth()+1,2)+'-'+dC(Cd.getDate(),2);}function yC()
{if(sC)
return;var Ed,Fd,Gd,s,Hd;var Id=new Date();var Jd=new Date();Jd.setTime(Id-0+parseInt(Ads_T[9],10));Ed=mD[1].split('#');Fd=Ed.length-1;Gd=',';for(s=1;s<Fd;s++)
{Hd=Ed[s].split(':');Gd+=Hd[0]+',';}sC=true;tC=';keyword='+escape(Ads_wrd) +';user-domain='+Ads_T[5] +';user-ip='+Ads_T[6] +';url='+escape(window.location.href) +';referrer='+escape(document.referrer) +';accept-language='+escape(Ads_T[7]) +';accept-charset='+escape(Ads_T[8]) +';user-agent='+escape(navigator.userAgent) +';browser-name='+escape(navigator.appName) +';browser-version='+escape(navigator.appVersion) +';flash-version='+iC(0) +';user-day='+(Id.getDay()==0?7:Id.getDay()) +';user-time='+wC(Id) +';user-date='+xC(Id) +';server-day='+(Jd.getDay()==0?7:Jd.getDay()) +';server-time='+wC(Jd) +';server-date='+xC(Jd) +';campaigns='+Gd +';';if(navigator.appVersion.substring(0,1)>'3')
tC+='java='+(navigator.javaEnabled()?'1':'0') +';screen-width='+screen.width +';screen-height='+screen.height +';window-width='+(window.innerWidth?window.innerWidth:document.body.clientWidth) +';window-height='+(window.innerWidth?window.innerHeight:document.body.clientHeight) +';color-depth='+screen.colorDepth +';';fC(1,'Environment values',tC);}function zC(Kd,r,Hb,Ld,Md,Nd,Od)
{var Pd;if((r>0)&&(Kd>0))
{Pd=((xD(Hb,Ld)<r)&&(kA||Od));if((Pd?1:0)==Md)
return Md;uC[Nd]=Pd;}return 2;}function aD(Qd,Rd,Sd,Md,Nd)
{var Pd;if(Qd.length>1)
{Pd=(Qd.indexOf('#'+Rd+'#')!=-1);Pd=Sd>0?!Pd:Pd;if((Pd?1:0)==Md)
return Md;uC[Nd]=Pd;}return 2;}function bD(Kd,Td,Hb,Ld,Md,Nd,Od)
{var Pd=true;if (typeof(Td)=='undefined')
Td=[];if (typeof(hB[Ads_wid])=='undefined')
hB[Ads_wid]=[];if(Kd>0&&Hb>0)
{if ((Td.length>0)&&(hB[Ads_wid].length==0))
{for (intI=0 ;intI<Td.length ;intI++)
{hB[Ads_wid][Td[intI][0]]=[Td[intI][1],Td[intI][2],Td[intI][3]]
if (Td[intI][0]==Hb)
{AIndex=intI;}}if (typeof(AIndex)=='undefined')
return 2
intReturn=zC(Kd,Td[AIndex][2],Td[AIndex][1],Ld,Md,Nd,Od);return intReturn;}else if (hB[Ads_wid].length>0)
{if (typeof(hB[Ads_wid][Hb])=='undefined')
return 2
intReturn=zC(Kd,hB[Ads_wid][Hb][1],hB[Ads_wid][Hb][0],Ld,Md,Nd,Od);return intReturn;}}return 2;}function cD(Qd,Sd,Md,Ud,Nd)
{if(Qd=='')
return 2;var s,Cb,Vd,Wd,Xd,Yd,Zd,Ae,Be;var Ce='!"%&\'()*+,-./:;<=>?@[\\]^{|}~§ ';var Pd=false;Qd=Qd.substr(1,Qd.length-2);var Fc=Qd.split('#');var r=Fc.length;if(r>0)
{if(Ud)
{Cb='';Yd=Ads_wrd.length;for(s=0;s<Yd;s++)
{Xd=Ads_wrd.charAt(s);if(Ce.indexOf(Xd)!=-1)
Xd='#';Cb+=Xd;}Cb='#'+Cb.toLowerCase()+'#';Vd=Cb;}else
{Cb='#'+Ads_T[5]+'#';Vd='#'+Ads_T[6]+'#';}for(s=0;(s<r)&&(Pd==false);s++)
{Ae=Fc[s].toLowerCase();Zd=false;if(Ae.substring(0,1)=='$')
{Ae=Ae.substring(1,Ae.length-1);Zd=true;}Wd=false;Be=Cb;if(Ae.substring(0,1)=='!')
{Ae=Ae.substring(1,Ae.length-1);Be=Vd;Wd=true;}if(Ud)
Ae='#'+Ae;if(!Wd)
Ae+='#';Pd=(Be.indexOf(Ae)!=-1);if(Zd&&Pd)
{Pd=false;s=r;}}Pd=Sd>0?!Pd:Pd;if((Pd?1:0)==Md)
return Md;uC[Nd]=Pd;}return 2;}function dD(De,Ee)
{var Fe=[];var Ge=0;var s,He;var r=De.length;for(s=0;s<r;s++)
{He=De[s];if(He>=0)
{Fe[Ge]=Ee[He];Ge++;}else if(He==-2)
{Ge--;Fe[Ge-1]=(Fe[Ge-1]&&Fe[Ge]);}else if(He==-4)
{Ge--;Fe[Ge-1]=(Fe[Ge-1]||Fe[Ge]);}else if(He==-3)
Fe[Ge-1]=(!Fe[Ge-1]);}return Fe[Ge-1];}function eD(Fc,Ie,Sd,Je,Ke,Md,Nd)
{var Pd,Nb,Le,Me,Ne,Oe,H,Pe;var Qe,Re;var s=0;var r=Fc.length;var Ee=[];var Se=Ie.toLowerCase();for(s=0;s<r;s++)
{Nb=Fc[s][0];Le=Fc[s][1];H=Fc[s][2];Pe=Fc[s][3];fC(1,'Profile/Environment -> Name,WishedValue,Type,Operator',Nb+','+Le+','+H+','+Pe);Qe=Se.indexOf(';'+Nb+'=');if(Qe>-1)
{Re=Ie.indexOf(';',Qe+1);if(Re>Qe)
Oe=unescape(Ie.substring(Qe+2+Nb.length,Re));else
Oe='';if(H==5)
H=1;if(H==1)
Me=0;else
Me='';if((Pe==9)||(Pe==10))
{Ne=Le.split(';');if(Ne.length==2)
{Le=Ne[0];Me=Ne[1];}else
Pe=0;}if(H==1)
{Oe=parseFloat(Oe);Le=parseFloat(Le);Me=parseFloat(Me);}if((Pe>5)&&(Pe<9))
{Oe=Oe.toLowerCase();Le=Le.toLowerCase();}if(Pe==0)
Pd=(Oe==Le)
else if(Pe==1)
Pd=(Oe!=Le)
else if(Pe==2)
Pd=(Oe<Le)
else if(Pe==3)
Pd=(Oe<=Le)
else if(Pe==4)
Pd=(Oe>Le)
else if(Pe==5)
Pd=(Oe>=Le)
else if(Pe==6)
Pd=(Oe.indexOf(Le)>-1);else if(Pe==7)
Pd=(Oe.indexOf(Le)<0);else if(Pe==8)
Pd=Oe.substr(0,Le.length-1)==Le;else if(Pe==9)
Pd=((Oe>=Le)&&(Oe<=Me))
else if(Pe==10)
Pd=((Oe<Le)||(Oe>Me))
}else
{Pd=false;}fC(1,'Profile/Environment -> result',Pd);if(Je==2)
Ee[s]=Pd;else
{if((Pd&&(Je==1))||(!Pd&&(Je==0)))
s=r;}}if(Je==2)
Pd=dD(Ke,Ee);Pd=Sd>0?!Pd:Pd;if((Pd?1:0)==Md)
return Md;uC[Nd]=Pd;return 2;}function fD(Te,Ue)
{var Id=new Date();var Jd=new Date();Jd.setTime(Id-0+parseInt(Ads_T[9],10));var Ve=Jd.getHours()*60+Jd.getMinutes();if(Te<Ue)
Pd=((Ve>=Te)&&(Ve<=Ue));else
Pd=((Ve>=Te)||(Ve<=Ue));return Pd;}function gD(We,Xe)
{var r=We.length;var Ye;if(typeof(We.Ads_klist)=='string')
Xe+=We.Ads_klist+'#';for(Ye=0;Ye<r;Ye++)
{try
{Xe=gD(We.frames[Ye],Xe);}catch(objError) {}}return Xe;}function hD(Fc,H,Hb,Od,Ze)
{var Md=Fc[0];var Sd=Fc[1];var Pd,Af,Bf,Cf,Df,Gd,Ed,Fd,s,Ef,Ff,Gf,Hf;uC=[true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true];if(Fc.length==0)
return true;fC(1,'Targeting',Fc);if(((Md>0)||(H==1))&&!((Md==1)&&(Fc[2]==0)&&(Fc[3]==1439)))
{Pd=fD(Fc[2],Fc[3]);fC(1,'Time',Pd);if((Pd?1:0)==Md)
return Pd;uC[0]=Pd;}Af=zC(1,Fc[4],Hb,(H==0)?2:9,Md,1,Od);fC(1,'Frequency (Max:'+Fc[4]+',actual:'+xD(Hb,(H==0)?2:9)+')',Af!=0);if(Af<2)
return Af==1;if(H==0)
{Af=zC(Fc[22]&1,IAS[4],Ads_wid,7,Md,12,Od);fC(1,'Frequency (WebSite)',Af!=0);if(Af<2)
return Af==1;Af=zC(Fc[22]&2,IAS[6],Ads_nid,8,Md,13,Od);fC(1,'Frequency (Network)',Af!=0);if(Af<2)
return Af==1;Af=bD(Fc[22]&4,IAS[17],KAS[Ze][13],12,Md,17,Od);fC(1,'Frequency (Family)',Af!=0);if(Af<2)
return Af==1;}Af=aD(Fc[6],Ads_T[0],Sd&1,Md,2);fC(1,'OS',Af!=0);if(Af<2)
return Af==1;Af=aD(Fc[7],Ads_T[1],Sd&2,Md,3);fC(1,'Browser',Af!=0);if(Af<2)
return Af==1;Af=aD(Fc[8],Ads_T[2],Sd&4,Md,4);fC(1,'Country',Af!=0);if(Af<2)
return Af==1;Af=aD(Fc[9],Ads_T[3],Sd&8,Md,5);fC(1,'Provider',Af!=0);if(Af<2)
return Af==1;Af=aD(Fc[26],Ads_T[12],Sd&1024,Md,16);fC(1,'DMA',Af!=0);if(Af<2)
return Af==1;if(Fc[10].length>1)
{Pd=((Fc[10].indexOf('#'+Ads_T[4]+'#')!=-1)||(Fc[10].indexOf('#%'+Ads_T[10]+'#')!=-1)||(Fc[10].indexOf('#$'+Ads_T[11]+'#')!=-1));if((Ads_nid==7)&&(Ads_T[4]<1)&&(Fc[10].indexOf('#$14658#')!=-1)) Pd=true;Pd=(Sd&16)>0?!Pd:Pd;fC(1,'Region',Pd);if((Pd?1:0)==Md)
return Md;uC[6]=Pd;}Af=cD(Fc[11],Sd&32,Md,false,7);fC(1,'Domain',Af!=0);if(Af<2)
return Af==1;Af=cD(Fc[12],Sd&64,Md,true,8);fC(1,'Keyword',Af!=0);if(Af<2)
return Af==1;if(Fc[13].length>0)
{Af=eD(Fc[13],';'+Ads_prf+';',Sd&128,Fc[15],Fc[17],Md,9);fC(1,'Profile',Af!=0);if(Af<2)
return Af==1;}if(Fc[14].length>0)
{yC();Af=eD(Fc[14],tC,Sd&256,Fc[16],Fc[18],Md,10);fC(1,'Environment',Af!=0);if(Af<2)
return Af==1;}intBwdLevel=0;intBwdTyp=Fc[27];intBwdUser=mD[10];intBwdIP=Ads_T[13];if (intBwdTyp==1){iD();intBwdLevel=intBwdUser;}if (intBwdTyp==2){intBwdLevel=intBwdIP;}if (intBwdTyp==3){iD();intBwdLevel=((intBwdIP>intBwdUser)&&(intBwdUser!=0))?intBwdUser:(intBwdIP!=0)?intBwdIP:intBwdUser;}if (intBwdTyp==4){iD();intBwdLevel=(intBwdIP>intBwdUser)?intBwdIP:intBwdUser;}if((intBwdTyp==5)&&(intBwdUser==intBwdIP))
{ iD();intBwdLevel=intBwdIP;}Af=aD(Fc[28],intBwdLevel,Sd&512,Md,11);fC(1,'Bandwidth ('+intBwdUser+':'+intBwdIP+':'+intBwdLevel+')',Af!=0);if(Af<2)
return Af==1;Hf=Fc[23];if((H==0)&&(Hf>0))
{Gd=Fc[24];if(Gd.length>2)
Gd=Gd.substring(1,Gd.length-1);Ed=Gd.split('#');Fd=Ed.length;Ef=-1;fC(1,'vor fngetklist','ok');strKList='#'+gD(top,'');fC(1,'nach fngetklist','ok');for(s=0;(s<Fd)&&(Ef<0);s++)
{Ff=(strKList.indexOf('#'+Ed[s]+'#')>-1);if((Ff?1:4)==Hf)
Ef=0;if((Ff?3:2)==Hf)
Ef=1;}if(Ef<0)
Ef=((Hf==1)||(Hf==4))?1:0;fC(1,'showed Camppaigns,In/Exclude',strKList+','+(Ef==1));if(Ef==Md)
return (Ef==1);uC[14]=(Ef==1);}s=Fc[25];if(s>0)
{Ff=IAS[8].indexOf('#'+s+':');if(Ff!=-1)
{Ff=IAS[8].indexOf(':',Ff);Gf=IAS[8].indexOf('#',Ff);Ff=IAS[8].substring(Ff+1,Gf);Gf=Ads_fcount[s];if(typeOf(Gf)=='undefined')
Gf=0;Pd=Ff>Gf;fC(1,'Family',Pd);if((Pd?1:0)==Md)
return Pd;uC[15]=Pd;}}if(Md!=2)
return (Md==0);else
return dD(Fc[19],uC);}function iD()
{if((vC==0)&&kA&&(document.cookie.toLowerCase().indexOf('bndlvl')==-1))
vC=1;}function jD()
{if(vC!=1)
return;if((iC(1)<6)||yA)
{fC(1,'Start BW-Test','Java');document.write('<applet codebase="'+tA[Ads_sec]+'/" code="bandwidth.class" id="bandwidth" name="bandwidth" width="0" height="0" mayscript="MAYSCRIPT"><param name="cbfunc" value="kD"></applet>');}else
{fC(1,'Start BW-Test','Flash');var Ua=window.location.hostname;document.write('<scr'+'ipt for="Ads_BWD" event="FSCommand(Jf,Kf)" language="VBScript"> \n on error resume next \n call Ads_BWD_DoFSCommand(Jf,Kf) \n </scr'+'ipt\>');document.write('<object id="Ads_BWD" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab" width="1" height="1">');document.write('<param name=movie value="'+tA[Ads_sec]+'/dat/dlv/bwdetect.swf?domain='+Ua+'&path='+tA[Ads_sec]+'"><param name=play value=true><param name=autoplay value=true>');document.write('<embed name="Ads_BWD" id="Ads_BWD" src="'+tA[Ads_sec]+'/dat/dlv/bwdetect.swf?domain='+Ua+'&path='+tA[Ads_sec]+'" play=true autoplay=true swLiveConnect=true width="1" height="1" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash">');document.write('</embed></object>');}vC=2;}function kD(If)
{oA=0;If*=8;document.cookie='BNDWDT='+If+wB(60*24*7);if(If==0)
oA=0;else if(If<9)
oA=1;else if(If<33)
oA=2;else if(If<65)
oA=3;else if(If<129)
oA=4;else if(If<385)
oA=5;else if(If<769)
oA=6;else if(If<1501)
oA=7;else if(If<3001)
oA=8;else
oA=9;document.cookie='BNDLVL='+oA+wB(60*24*7);}function Ads_BWD_DoFSCommand(Jf,Kf)
{kD(Kf/8);}function lD()
{var Lf=new Date();document.writeln('<scr'+'ipt language="Javascript"><!--');document.writeln('nA=new Date();');document.writeln('/'+'/--></scr'+'ipt><scr'+'ipt language="Javascript" src="'+tA[Ads_sec]+'/dat/dlv/aslprebwd.js?'+Lf.getTime()+'0"></scr'+'ipt>');}function Ads_PreBandwidth()
{var Mf=new Date();var Nf=Math.round((8026/((Mf.getTime()-nA.getTime()+1)/1000))/1024);fC(1,'Pre BW-Test',Nf);kD(Nf);qB();}
